#!/bin/bash

echo "🔧 Fixing Google Secrets in Supabase"
echo "====================================="
echo ""
echo "Your current secrets show that GOOGLE_ACCESS_TOKEN, GOOGLE_APPLICATION_CREDENTIALS,"
echo "and VERTEX_AI_KEY are all set to the same value (same hash)."
echo ""
echo "To fix this, you need to get proper credentials:"
echo ""
echo "OPTION 1: Get a fresh access token (expires after ~1 hour)"
echo "--------------------------------------------------------"
echo "If you have gcloud CLI:"
echo "  gcloud auth login"
echo "  gcloud config set project sigdesk-1753801804417"
echo "  npx supabase secrets set GOOGLE_ACCESS_TOKEN=\"\$(gcloud auth print-access-token)\""
echo ""
echo "OPTION 2: Create a service account (permanent solution)"
echo "-------------------------------------------------------"
echo "1. Go to: https://console.cloud.google.com/iam-admin/serviceaccounts?project=sigdesk-1753801804417"
echo "2. Create service account with Vertex AI User role"
echo "3. Download JSON key"
echo "4. npx supabase secrets set GOOGLE_APPLICATION_CREDENTIALS=\"\$(cat service-account-key.json)\""
echo ""
echo "OPTION 3: Use OAuth client secret"
echo "---------------------------------"
echo "Since you have OAuth Client ID: 828236259059-bdelovhuc12rgtavs7c5j9o7ftjgtof1.apps.googleusercontent.com"
echo "1. Get the client secret from Google Console"
echo "2. npx supabase secrets set GOOGLE_OAUTH_CLIENT_SECRET=\"your-secret-here\""
echo ""
echo "After updating, redeploy: npx supabase functions deploy vertex-ai-visual --no-verify-jwt"
