#!/bin/bash

echo "🔑 Google Authentication Options for Imagen"
echo "==========================================="
echo ""
echo "You have OAuth Client Secret set, but we need an access token."
echo ""
echo "FASTEST OPTION: Use gcloud CLI"
echo "-------------------------------"
echo "1. Install gcloud: https://cloud.google.com/sdk/docs/install"
echo ""
echo "2. Run these commands:"
echo "   gcloud auth login"
echo "   gcloud config set project sigdesk-1753801804417" 
echo "   gcloud auth application-default login"
echo ""
echo "3. Get and set the access token:"
echo "   ACCESS_TOKEN=\$(gcloud auth print-access-token)"
echo "   npx supabase secrets set GOOGLE_ACCESS_TOKEN=\"\$ACCESS_TOKEN\""
echo ""
echo "4. Redeploy the function:"
echo "   npx supabase functions deploy vertex-ai-visual --no-verify-jwt"
echo ""
echo "Note: Access tokens expire after ~1 hour, so this is temporary."
echo ""
echo "PERMANENT OPTION: Service Account"
echo "----------------------------------"
echo "Create a service account in Google Cloud Console"
echo "and set GOOGLE_APPLICATION_CREDENTIALS with the JSON key."
echo ""
echo "==========================================="
