[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
  "echo 'FORCE CACHE BUST: $(date +%s)'",
  "rm -rf node_modules .npm package-lock.json",
  "npm cache clean --force",
  "npm install --verbose --no-cache"
]

[phases.build]
cmds = [
  "echo 'Building SignalDesk Backend'",
  "echo 'Cache Bust Token: FORCE_REBUILD_2025_01_13_V1'",
  "ls -la"
]

[start]
cmd = "node server.js"

[providers]
node = false