# NIXPACKS OVERRIDE - FORCE BUILD WITHOUT DOCKER
# This completely bypasses any Dockerfile

[phases.setup]
nixPkgs = ["nodejs-20_x"]
aptPkgs = []

[phases.install]
# FORCE CLEAN BUILD - NO CACHE
cmds = [
    "echo 'NIXPACKS BUILD - NOT DOCKER'",
    "echo 'Build timestamp: '$(date)",
    "rm -rf node_modules",
    "rm -rf package-lock.json", 
    "rm -rf .npm",
    "rm -rf /app/node_modules/.cache || true",
    "npm install --no-cache --verbose"
]

[phases.build]
cmds = ["echo 'Build complete - using Nixpacks'"]

[start]
cmd = "node server.js"

[variables]
NODE_ENV = "production"
NIXPACKS_NO_CACHE = "true"