[build]
builder = "NIXPACKS"
nixpacksConfigPath = "./nixpacks.toml"
buildCommand = "echo 'FORCE REBUILD $(date)' && npm ci"
watchPatterns = ["!Dockerfile*", "!dockerfile*", "!DOCKERFILE*"]

[deploy]
startCommand = "node server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 45
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[[services]]
name = "backend"
builder = "NIXPACKS"