# Railway TOML configuration - takes precedence over railway.json
# Forces use of our custom Dockerfile without cache mounts

[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 45
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5