#!/bin/bash

echo "========================================="
echo "SignalDesk Supabase Setup Script"
echo "========================================="
echo ""
echo "This script will set up your Supabase database with all required tables"
echo "for the Opportunity Engine and MCPs."
echo ""
echo "You have two options to run the SQL:"
echo ""
echo "OPTION 1: Using Supabase Dashboard (Recommended)"
echo "1. Go to your Supabase dashboard: https://app.supabase.com"
echo "2. Select your project (zskaxjtyuaqazydouifp)"
echo "3. Go to SQL Editor (left sidebar)"
echo "4. Click 'New Query'"
echo "5. Copy and paste the contents of setup-supabase-schema.sql"
echo "6. Click 'Run' to execute"
echo ""
echo "OPTION 2: Using psql command line"
echo "Run this command:"
echo ""
echo "psql 'postgresql://postgres.[PROJECT_REF]:[PASSWORD]@aws-0-us-west-1.pooler.supabase.com:6543/postgres' -f setup-supabase-schema.sql"
echo ""
echo "Replace [PROJECT_REF] and [PASSWORD] with your actual values."
echo ""
echo "After setting up the database, you'll need to get your database connection string:"
echo ""
echo "1. Go to Settings > Database in your Supabase dashboard"
echo "2. Copy the 'Connection string' (URI format)"
echo "3. Update the DATABASE_URL in your .env files and MCP configurations"
echo ""
echo "Your project reference appears to be: zskaxjtyuaqazydouifp"
echo "Your Supabase URL is: https://zskaxjtyuaqazydouifp.supabase.co"
echo ""
echo "Press Enter to continue..."
read

echo "Opening the SQL file for you to copy..."
cat setup-supabase-schema.sql