services:
  - type: web
    name: signaldesk-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres:MUmjKBxTiecMPpYVgwGsZEKyFfyFbxqV@crossover.proxy.rlwy.net:56706/railway
      - key: CLAUDE_API_KEY
        sync: false
      - key: JWT_SECRET
        value: signaldesk-jwt-secret-2024