# Force Nixpacks build without Docker - Breaking Railway cache
[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-9_x"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "echo 'NIXPACKS BUILD - NOT DOCKER - $(date)'",
    "echo 'Clearing all caches...'",
    "rm -rf node_modules package-lock.json .npm /tmp/.npm",
    "npm cache clean --force",
    "echo 'Installing dependencies without cache...'",
    "npm install --no-cache --prefer-offline --no-audit --no-fund --verbose"
]

[phases.build]
dependsOn = ["install"]
cmds = [
    "echo 'Build phase complete - Nixpacks'",
    "ls -la"
]

[start]
cmd = "node server.js"

[variables]
NODE_ENV = "production"
NPM_CONFIG_CACHE = "/tmp/.npm"
NPM_CONFIG_PREFER_OFFLINE = "true"
NIXPACKS_BUILD = "true"
NO_DOCKER = "true"