-- Create executive_synthesis table to persist synthesis data
CREATE TABLE IF NOT EXISTS executive_synthesis (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id VARCHAR(255) NOT NULL,
  organization_name VARCHAR(255) NOT NULL,
  synthesis_data JSONB NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

-- Create index for efficient lookups by organization
CREATE INDEX IF NOT EXISTS idx_executive_synthesis_org
  ON executive_synthesis(organization_id);

CREATE INDEX IF NOT EXISTS idx_executive_synthesis_created
  ON executive_synthesis(created_at DESC);

-- Enable RLS
ALTER TABLE executive_synthesis ENABLE ROW LEVEL SECURITY;

-- Create policies for authenticated users
CREATE POLICY "Users can view all synthesis"
  ON executive_synthesis FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Users can insert synthesis"
  ON executive_synthesis FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Users can update synthesis"
  ON executive_synthesis FOR UPDATE
  TO authenticated
  USING (true);

-- Add comment for documentation
COMMENT ON TABLE executive_synthesis IS 'Stores executive intelligence synthesis reports generated by the pipeline';
