import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
import { corsHeaders, handleCors, jsonResponse, errorResponse } from '../_shared/cors.ts'

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!
const SUPABASE_SERVICE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const GOOGLE_API_KEY = Deno.env.get('GOOGLE_API_KEY')!

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY)

Deno.serve(async (req: Request) => {
  const corsResponse = handleCors(req)
  if (corsResponse) return corsResponse

  try {
    const { contentId, regenerate } = await req.json()

    if (!contentId) return errorResponse('contentId is required', 400)

    // Fetch content item
    const { data: item, error: fetchError } = await supabase
      .from('content_library')
      .select('id, title, content_type, content, organization_id, cover_image_url')
      .eq('id', contentId)
      .single()

    if (fetchError || !item) return errorResponse('Content not found', 404)

    // Return existing if not regenerating
    if (item.cover_image_url && !regenerate) {
      return jsonResponse({ success: true, coverImageUrl: item.cover_image_url })
    }

    console.log(`🎨 Generating cover image for: ${item.title}`)

    // Get org name for prompt context
    let orgName = ''
    if (item.organization_id) {
      const { data: org } = await supabase
        .from('organizations')
        .select('name')
        .eq('id', item.organization_id)
        .single()
      orgName = org?.name || ''
    }

    const contentType = (item.content_type || 'general').replace(/-/g, ' ')
    const title = item.title || 'Untitled'

    const prompt = `Create a professional cover image for a ${contentType} titled "${title}"${orgName ? ` for ${orgName}` : ''}.

STRICT RULES:
- NO people, faces, hands, bodies, or silhouettes
- NO text, words, letters, or typography of any kind
- NO recognizable logos or brand marks
- Pure abstract/conceptual imagery only

STYLE:
- Dark, sophisticated background (deep navy, charcoal, or near-black)
- Subtle geometric shapes, gradients, and light accents
- Modern editorial design aesthetic
- Clean composition with breathing room
- Accent colors that feel corporate and premium
- 16:9 aspect ratio, 1200x630 pixels

The image should feel like a premium magazine cover or a high-end consulting firm's report cover — sophisticated, abstract, and visually striking.`

    // Call Gemini 2.5 Flash Image (nano banana) — same as grounded-art
    const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image:generateContent?key=${GOOGLE_API_KEY}`

    const geminiResponse = await fetch(endpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ role: 'user', parts: [{ text: prompt }] }],
        generationConfig: {
          responseModalities: ['IMAGE', 'TEXT'],
          temperature: 1.0,
          topP: 0.95,
          topK: 40,
          maxOutputTokens: 8192,
        },
      }),
    })

    if (!geminiResponse.ok) {
      const errText = await geminiResponse.text()
      console.error('Gemini API error:', geminiResponse.status, errText)
      return errorResponse(`Gemini API error: ${geminiResponse.status}`, 500)
    }

    const data = await geminiResponse.json()
    const parts = data.candidates?.[0]?.content?.parts
    if (!parts) return errorResponse('No content in Gemini response', 500)

    // Extract image
    let imageBase64 = ''
    let mimeType = 'image/png'
    for (const part of parts) {
      if (part.inlineData?.data) {
        imageBase64 = part.inlineData.data
        mimeType = part.inlineData.mimeType || 'image/png'
      }
    }

    if (!imageBase64) return errorResponse('No image generated by Gemini', 500)

    // Upload to storage
    const fileExt = mimeType.includes('jpeg') || mimeType.includes('jpg') ? 'jpg' : 'png'
    const fileName = `covers/${item.organization_id || 'global'}/${contentId}-${Date.now()}.${fileExt}`

    const binaryString = atob(imageBase64)
    const bytes = new Uint8Array(binaryString.length)
    for (let i = 0; i < binaryString.length; i++) {
      bytes[i] = binaryString.charCodeAt(i)
    }

    // Delete old cover if regenerating
    if (regenerate && item.cover_image_url) {
      try {
        const oldPath = item.cover_image_url.split('/content-library/')[1]
        if (oldPath) await supabase.storage.from('content-library').remove([oldPath])
      } catch { /* ignore */ }
    }

    const { error: uploadError } = await supabase.storage
      .from('content-library')
      .upload(fileName, bytes, { contentType: mimeType, upsert: true })

    if (uploadError) {
      console.error('Upload error:', uploadError)
      return errorResponse(`Upload failed: ${uploadError.message}`, 500)
    }

    const { data: { publicUrl } } = supabase.storage
      .from('content-library')
      .getPublicUrl(fileName)

    // Save URL to DB
    await supabase
      .from('content_library')
      .update({ cover_image_url: publicUrl })
      .eq('id', contentId)

    console.log(`✅ Cover image generated: ${publicUrl}`)

    return jsonResponse({ success: true, coverImageUrl: publicUrl })
  } catch (err: any) {
    console.error('generate-cover-image error:', err)
    return errorResponse(err.message || 'Internal error', 500)
  }
})
